name: Destroy RDS Infra 

on:
  workflow_dispatch:

jobs:
  destroy-rds:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      #AWS CREDENTIALS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION_DEFAULT }}

      #Terraform execution
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        # env:
        #   TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
        #   TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
